<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php

  echo $this->headScript()
                  ->prependFile($this->baseUrl('jsalegra/extjs_6_5\theme-classic\theme-classic.js'))
                  ->prependFile($this->baseUrl('jsalegra/extjs_6_5/ext-all.js'));

  echo $this->headLink()
                  ->prependStylesheet('/cssalegra/styles-min.css')
                  ->prependStylesheet('/cssalegra/ext-theme-gray-all2.css')
                  ->prependStylesheet('/cssalegra/theme-triton/theme-triton-all.css');
?>
</head>
<body>

  <script>
  var menu = Ext.create('Ext.menu.Menu', {
      plain: true,
      layout: 'hbox',
      floating: false,
      flex: true,
      style: {
           overflow: 'visible'
       },
      items: [{
          text: 'Inicio'
      },{
          text: 'Ingresos'
      },{
          text: 'Gastos'
      },{
          text: 'Contactos',
          menu:[{
            text: 'Todos',
            handler: function() {
                window.location = '/client/';
            }
          },{
            text: 'Clientes',
            handler: function() {
                window.location = '/client/view-client';
            }
          },{
            text: 'Proveedores',
            handler: function() {
                window.location = '/client/view-provider';
            }
          }]
      },{
          text: 'Inventario'
      },{
          text: 'Bancos'
      },{
          text: 'Categorías'
      },{
          text: 'Reportes'
      },{
          xtype: 'tbspacer',
          width: '100px'
      },{
          text: 'Nuevo'
      }]

      ,renderTo: document.body
      ,region: 'north'
  });

  </script>

  <?php  echo $this->layout()->content; ?>

</body>
</html>
