<script>

  var list  = <?= Zend_Json::encode($this->entries) ?>;
  console.log(list);

  var storePriceList = Ext.create('Ext.data.Store', {
      storeId: 'storePriceList',
      autoLoad: true,
      proxy: {
          type: 'memory',
          reader:{
            type: 'json',
            rootProperty: 'price_list'
          }
      },
      data: list
  });

  var storePaymentTerm = Ext.create('Ext.data.Store', {
      storeId: 'storePaymentTerm',
      autoLoad: true,
      proxy: {
          type: 'memory',
          reader:{
            type: 'json',
            rootProperty: 'payment_term'
          }
      },
      data: list
  });

  var storeSeller = Ext.create('Ext.data.Store', {
      storeId: 'storeSeller',
      autoLoad: true,
      proxy: {
          type: 'memory',
          reader:{
            type: 'json',
            rootProperty: 'seller'
          }
      },
      data: list
  });

  var spacer = {
                 xtype: 'tbspacer',
                 height: '25px',
               };

  var form = Ext.create('Ext.form.Panel', {
      title: 'Editar cliente',
			layout: 'hbox',
			bodyBorder: false,
			margin: '10 25 10 25',
			defaults: {
					anchor: '100%'
			},
      //flex: 1,
      //renderTo: Ext.getBody(),
      items: [{
			   xtype: 'form',
			   layout: 'anchor',
			   labelAlign: 'top',
				 flex: 1,
				 border: false,
				 margin: '10 25 10 25',
		   items: [{
		          xtype: 'textarea',
		          name: 'name',
		          fieldLabel: 'Nombre',
		          allowBlank: false
		      }, {
		          xtype: 'textarea',
		          name: 'nit',
		          fieldLabel: 'NIT',
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'address',
		          fieldLabel: 'Dirección',
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'city',
		          fieldLabel: 'Ciudad',
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'email',
		          fieldLabel: 'Email Address',
		          vtype: 'email',
							allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'tel01',
		          fieldLabel: 'Teléfono 01',
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'tel02',
		          fieldLabel: 'Teléfono 02',
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'fax',
		          fieldLabel: 'Fax',
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'phone',
		          fieldLabel: 'Celular',
		          allowBlank: true
		      }]
				},{
					xtype: 'tbspacer',
					width: '15px'
				},{
				   xtype: 'form',
				   layout: 'anchor',
				   labelAlign: 'top',
					 flex: 1,
					 border: false,
					 margin: '10 25 10 25',
				   items: [{
				          xtype: 'combobox',
				          name: 'price_list',
				          fieldLabel: 'Lista de precios',
				          allowBlank: true,
                  store: storePriceList,
                  displayField: 'description',
                  valueField: 'id'
				      },{
				          xtype: 'combobox',
				          name: 'seller',
				          fieldLabel: 'Vendedor',
				          allowBlank: true,
                  store: storeSeller,
                  displayField: 'name',
                  valueField: 'id'
				      },{
				          xtype: 'combobox',
				          name: 'payment_term',
				          fieldLabel: 'Términos de pago',
				          allowBlank: true,
                  store: storePaymentTerm,
                  displayField: 'description',
                  valueField: 'id'
				      },{
				          xtype: 'checkbox',
				          name: 'client',
				          fieldLabel: 'Cliente',
				          allowBlank: true
				      },{
				          xtype: 'checkbox',
				          name: 'provider',
				          fieldLabel: 'Provider',
				          allowBlank: true
				      },{
				          xtype: 'textarea',
				          name: 'comment',
				          fieldLabel: 'Observaciones',
				          allowBlank: true
				      },{
				          xtype: 'checkbox',
				          name: 'account_status',
				          fieldLabel: 'Incluir estado de cuenta',
				          allowBlank: true
				      }]}],
			url: '/client/add',
			method: 'POST',
      buttons: [{
            text: 'Guardar',
            handler: function() {
                var form = this.up('form').getForm();
                if (form.isValid()) {
                    form.submit({
												method: 'POST',
												success: function(data) {
													 Ext.Msg.alert('Cliente creado');
													 window.location = '/client/';
												},
												failure: function(data) {
														Ext.Msg.alert('Cliente creado.');
														window.location = '/client/';
												}
                    });
                } else {
                    Ext.Msg.alert( "Favor revise los campos del formulario" );
                }
            	}
	      		},{
		            text: 'Guardar y crear otro',
		            handler: function() {
		                var form = this.up('form').getForm();
		                if (form.isValid()) {
		                    form.submit({
														method: 'POST',
														success: function(data) {
															 Ext.Msg.alert('Cliente creado');
															 form.reset();
														},
														failure: function(data) {
																Ext.Msg.alert('Cliente creado.');
																form.reset();
														}
		                    });
		                } else {
		                    Ext.Msg.alert( "Favor revise los campos del formulario" );
		                }
		            	}
			      		},{
		            text: 'Cancelar',
		            handler: function() {
		                window.location = '/client/';
		            	}
	      		}]
  });



  Ext.define('Main', {
      extend: 'Ext.container.Container',
      xtype: 'app-main'
      ,items: [spacer,
               form,
               spacer]
  });


  Ext.application({
      name: 'Clients',

      launch : function() {
          Ext.create("Main", {
              renderTo : Ext.getBody()
          });
      }
  });

</script>
