<script>
	var dataServer = <?= Zend_Json::encode($this->entries) ?>;

	var storeClient = dataServer['client'];

	var storePriceList = Ext.create('Ext.data.Store', {
			storeId: 'storePriceList',
			autoLoad: true,
			proxy: {
					type: 'memory',
					reader:{
						type: 'json',
						rootProperty: 'price_list'
					}
			},
			data: dataServer
	});

	var storePaymentTerm = Ext.create('Ext.data.Store', {
			storeId: 'storePaymentTerm',
			autoLoad: true,
			proxy: {
					type: 'memory',
					reader:{
						type: 'json',
						rootProperty: 'payment_term'
					}
			},
			data: dataServer
	});

	var storeSeller = Ext.create('Ext.data.Store', {
			storeId: 'storeSeller',
			autoLoad: true,
			proxy: {
					type: 'memory',
					reader:{
						type: 'json',
						rootProperty: 'seller'
					}
			},
			data: dataServer
	});

  var spacer = {
                 xtype: 'tbspacer',
                 height: '25px',
               };

  var form = Ext.create('Ext.form.Panel', {
      title: 'Editar cliente',
			layout: 'hbox',
			bodyBorder: false,
			margin: '10 25 10 25',
			defaults: {
					anchor: '100%'
			},
      //flex: 1,
      //renderTo: Ext.getBody(),
      items: [{
			   xtype: 'form',
			   layout: 'anchor',
			   labelAlign: 'top',
				 flex: 1,
				 border: false,
				 margin: '10 25 10 25',
		   items: [{
		          xtype: 'textarea',
		          name: 'name',
		          fieldLabel: 'Nombre',
							value: storeClient.name,
		          allowBlank: false
		      }, {
		          xtype: 'textarea',
		          name: 'nit',
		          fieldLabel: 'NIT',
							value: storeClient.nit,
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'address',
		          fieldLabel: 'Dirección',
							value: storeClient.address,
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'city',
		          fieldLabel: 'Ciudad',
							value: storeClient.city,
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'email',
		          fieldLabel: 'Email Address',
		          vtype: 'email',
							value: storeClient.email,
							allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'tel01',
		          fieldLabel: 'Teléfono 01',
							value: storeClient.tel01,
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'tel02',
		          fieldLabel: 'Teléfono 02',
							value: storeClient.tel02,
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'fax',
		          fieldLabel: 'Fax',
							value: storeClient.fax,
		          allowBlank: true
		      },{
		          xtype: 'textarea',
		          name: 'phone',
		          fieldLabel: 'Celular',
							value: storeClient.phone,
		          allowBlank: true
		      }]
				},{
					xtype: 'tbspacer',
					width: '15px'
				},{
				   xtype: 'form',
				   layout: 'anchor',
				   labelAlign: 'top',
					 flex: 1,
					 border: false,
					 margin: '10 25 10 25',
				   items: [{
				          xtype: 'combobox',
				          name: 'price_list',
				          fieldLabel: 'Lista de precios',
									value: storeClient.price_list,
				          allowBlank: true,
									store: storePriceList,
									displayField: 'description',
									valueField: 'id'
				      },{
				          xtype: 'combobox',
				          name: 'seller',
				          fieldLabel: 'Vendedor',
									value: storeClient.seller,
				          allowBlank: true,
									store: storeSeller,
									displayField: 'name',
									valueField: 'id'
				      },{
				          xtype: 'combobox',
				          name: 'payment_term',
				          fieldLabel: 'Términos de pago',
									value: storeClient.payment_term,
				          allowBlank: true,
									store: storePaymentTerm,
									displayField: 'description',
									valueField: 'id'
				      },{
				          xtype: 'checkbox',
				          name: 'client',
				          fieldLabel: 'Cliente',
									value: (storeClient.client == 1) ? 'on' : 0,
				          allowBlank: true
				      },{
				          xtype: 'checkbox',
				          name: 'provider',
				          fieldLabel: 'Provider',
									value: (storeClient.provider == 1) ? 'on' : 0,
				          allowBlank: true
				      },{
				          xtype: 'textarea',
				          name: 'comment',
				          fieldLabel: 'Observaciones',
									value: storeClient.comment,
				          allowBlank: true
				      },{
				          xtype: 'checkbox',
				          name: 'account_status',
				          fieldLabel: 'Incluir estado de cuenta',
									value: (storeClient.account_status == 1) ? 'on' : 0,
				          allowBlank: true
				      }]}],
			url: '/client/edit',
			method: 'POST',
      buttons: [{
            text: 'Guardar',
            handler: function() {
                var form = this.up('form').getForm();
                if (form.isValid()) {
                    form.submit({
												method: 'POST',
												params:{
														id: storeClient.id
												},
												success: function(data) {
													 Ext.Msg.alert('Cliente actualizado');
													 window.location = '/client/';
												},
												failure: function(data) {
														Ext.Msg.alert('Cliente actualizado.');
														window.location = '/client/';
												}
                    });
                } else {
                    Ext.Msg.alert( "Favor revise los campos del formulario" );
                }
            	}
      		},{
	            text: 'Cancelar',
	            handler: function() {
	                window.location = '/client/';
	            	}
	      		}]
  });



  Ext.define('Main', {
      extend: 'Ext.container.Container',
      xtype: 'app-main'
      ,items: [spacer,
               form,
               spacer]
  });


  Ext.application({
      name: 'Clients',

      launch : function() {
          Ext.create("Main", {
              renderTo : Ext.getBody()
          });
      }
  });

</script>
