<?php
	header('Content-Type: text/html; charset=utf-8');
/*
	<table>
		<head>
			<tr>
				<td>Name</td>
				<td>NIT</td>
				<td>Telephone 1</td>
				<td>Comments</td>
				<td>Actions</td>
			</tr>
		</head>
		<body>
		*/

		echo "<a href='client/add'>Add</a><br/><br/>";
		foreach ($this->entries as $entry)
		{
			/*
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>*/
			echo "ID: ".htmlentities($this->escape($entry->getId()))."<br/>";
			echo "Name: ".htmlentities($this->escape($entry->getName()))."<br/>";
			echo "Nit: ".htmlentities($this->escape($entry->getNit()))."<br/>";
			echo "Telephone 1: ".htmlentities($this->escape($entry->getTel01()))."<br/>";
			echo "Comment: ".htmlentities($this->escape($entry->getComment()))."<br/>";
			echo "<form action='edit' method='get'>
						  Choose your favorite subject:
							<button name='watch' type='submit' >Watch</button>
						  <button name='edit' type='submit' >Edit</button>
						  <button name='delete' type='submit' >Delete</button>
						</form><hr><br/>";

		}
		/*
		</body>
	</table>
	<a href="https://www.google.com">Google</a>*/

?>
