

	<script>
		var clientData = <?= Zend_Json::encode($this->entries) ?>;

		Ext.require([
		    'Ext.grid.*',
		    'Ext.data.*',
		    'Ext.util.*',
		    'Ext.state.*',
		    'Ext.form.*'
		]);


		Ext.define('ClientModel', {
				extend: 'Ext.data.Model',
				fields: [
						{name: 'id', type: 'int'},
						{name: 'name', type: 'string'},
						{name: 'nit', type: 'string'},
						{name: 'tel01', type: 'string'},
						{name: 'comment', type: 'string'}
				]
		});


		var store = Ext.create('Ext.data.Store', {
				storeId: 'clientStore',
				model: 'ClientModel',
				proxy: {
						type: 'memory',
						reader:{
							type: 'json'
						}
				},
				data: clientData
		});

		var menu = Ext.create('Ext.menu.Menu', {
	      plain: true,
	      layout: 'hbox',
	      floating: false,
	      flex: true,
				border: false,
				margin: '10 25 10 25',
	      style: {
	           overflow: 'visible'
	       },
	      items: [{
	          text: '+Nuevo Cliente',
						xtype: 'button',
						handler: function() {
                window.location = '/client/add';
            }
	      },{
	          text: 'Importar desde excel'
	      },{
	          xtype: 'tbspacer',
						width: '25px'
	      }]

	      //,renderTo: document.body
	      ,region: 'north'
	  });

    var grid = Ext.create('Ext.grid.Panel', {
			  //renderTo: document.body,
				region: 'center',
        store:  store,
				plain: false,
				align : 'center',
				width: '85%',
				floating: false,
				flex: 1,
				border: false,
				margin: '10 25 10 25',
				style: {
						 overflow: 'visible'
				 },
        columns: [
					{
							//style: 'margin: 1em auto 2em; width: 85%; height:30px;',
	            xtype: 'checkcolumn',
	            dataIndex: 'selected',
							flex : 0
	        },{
            header: 'Nombre',
            dataIndex: 'name',
						text: 'Name',
            flex: 1

        }, {
            header: 'Nit',
            dataIndex: 'nit',
						sortable: true
						,flex: 1
        }, {
            header: 'Teléfono 01',
            dataIndex: 'tel01',
						sortable: true
						,flex: 1
        }, {
            header: 'Observaciones',
            dataIndex: 'comment',
						sortable: true
						,flex: 1
        },{
					header: 'Acciones',
					xtype: 'actioncolumn',
					align: 'center',
					layout: 'hbox',
					items: [{
								icon: "/images/zoom.png",
								text: "zoom",
								tooltip: "Ver",
								stopSelection: false,
								handler: function(grid, rowIndex, colIndex) {
										console.log("s: " + grid.store.getAt(rowIndex).data.name);
								}
							},{
								icon: "/images/page_edit.png",
								text: "edit",
								tooltip: "Editar",
								handler: function(grid, rowIndex, colIndex) {
										var id = grid.store.getAt(rowIndex).data.id;
										window.location = '/client/edit?id='+ escape(id);
										/*
										Ext.Ajax.request({
										    url: '/client/edit',
										    params: {
										        id: id
										    },
										    success: function(response){
										        var text = response.responseText;
														console.log(id);
										        // process server response here
										    }
										})*/
								}
							},{
								icon: "/images/delete.png",
								text: "delete",
								tooltip: "Eliminar",
								handler: function(grid, rowIndex, colIndex) {
										var id = grid.store.getAt(rowIndex).data.id;
										var name = grid.store.getAt(rowIndex).data.name;
										var confirmWin = Ext.MessageBox;
										/*Ext.Msg.confirm('Confirmación', '¿Está seguro de eliminar a '+ name +' como cliente?',
										function(btn){
											if(btn === 'yes'){
												window.location = '/client/delete?id=' + escape(id);
											}
										});*/
										Ext.Msg.show({
											title: 'Confirmación',
											msg: '¿Está seguro de eliminar a '+ name +' como cliente?',
											buttons: Ext.Msg.YESNO,
											buttonText: {
												yes: 'Si'
											},
											fn: function(btnValue, inputText, showConfig){
												if(btnValue === 'yes'){
													window.location = '/client/delete?id=' + escape(id);
												}
											}
										});

								}
					}],
					flex: 1
				}]
    });


		var spacer = {
									 xtype: 'tbspacer',
									 height: '25px'
								 };

	 Ext.define('Main', {
	     extend: 'Ext.container.Container',
	     xtype: 'app-main'
	     ,items: [spacer,
				 				menu,
								spacer,
				 				grid ]
	 });


	 Ext.application({
	     name: 'Clients',

	     launch : function() {
	         Ext.create("Main", {
	             renderTo : Ext.getBody()
	         });
	     }
	 });


</script>
